### ISSUE TITLE
SSL_connect: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed (OpenSSL::SSL::Error)

### ISSUE THREAD

**Issue by pythonohtyp** [anapsix/get-cloudflare-logs#2]
when I run ./feron-0.3.0-linux-amd64 -z "2cxxxxxxx4398xxxxxxxx07ef" -e "xxxx@rxxyxxxxxpa.com" -k "0753aab544d6xxxxxxxxxxxx" in shell ,I get this error Unhandled exception: SSL_connect: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed (OpenSSL::SSL::Error)  , why???

**Comment by anapsix** [comment]
try checking if your system has a problem validating Cloudflare's cert with `curl -v https://api.cloudflare.com/client/v4`

**Comment by anapsix** [comment]
if curl does not have any issues connecting / validating Cloudflare cert, please reopen in Feron: https://github.com/anapsix/feron/issues
